### ISSUE TITLE
TypeError: can only join an iterable

### ISSUE THREAD

**Issue by coonsmatthew** [mnrkbys/macosac#1]
When I try to run this application, I'm presented with an error related to a file write command. 

My belief is that this error relates to the inability to read a plist file (after I run as sudo & give terminal access to the entire filesystem).

The command I'm running is: 
`sudo /usr/bin/python2.7 macosac.py`

The error I see is (I redacted the name of the plist): 

```Retrieving artifact file stat...
[Errno 13] Permission denied: '/Library/LaunchDaemons/12345.plist'
Checking outputdir free space...
Saving file stat...
Traceback (most recent call last):
  File "macosac.py", line 494, in <module>
    main()
  File "macosac.py", line 472, in main
    save_file_stat(outputdir, file_stat_list)
  File "macosac.py", line 178, in save_file_stat
    fp.write('\n'.join(file_stat_list))
TypeError: can only join an iterable
```

Do you know what may be happening here? 

Thank you.

**Comment by mnrkbys** [comment]
I don't know that. I need more information.

What is your OS environment?
Can you access "/Library/LaunchDaemons/12345.plist" as root with "ls -al" and "stat"?
When does the "Permission denied" error displayed?

**Comment by mnrkbys** [comment]
No reply. Close this.
