### ISSUE TITLE
No firefox data collected with default macosac.ini

### ISSUE THREAD

**Issue by 4n6ist** [mnrkbys/macosac#2]
Hi Minoru-san,

Not code issue, but I have realized that it fails to collect firefox data with default configuration due to the following line 

```
[firefox]
file1_1 = /Users/*/Library/Application Support/Firefox/Profiles/*.*
```

I have modified as follows and now it seems working (maybe I should describe the path more specifically)

```
[firefox]
file1_1 = /Users/*/Library/Application Support/Firefox/Profiles/*.*/*
```

**Comment by mnrkbys** [comment]
Thanks for reporting, 4n6ist.
I've fixed this issue.
