### ISSUE TITLE
utmpx is not being collected

### ISSUE THREAD

**Issue by ydkhatri** [mnrkbys/macosac#5]
It seems the file utmpx is not being collected, probably something to do with rsync. 

```
ykhatri@Balloon code % sudo /usr/bin/python2 macosac/macosac.py -o . -t dir  -c utmpx --debug
Output dir: /Users/ykhatri/Desktop/code/192-168-1-103_20210711_144142
Debug log: /Users/ykhatri/Desktop/code/macosac/debug.log

Finding aritifact files for backup...
Retrieving artifact file stat...
total_size:  4096
Checking outputdir free space...
Saving file stat...
Copying artifact files...
building file list ... 
5 files to consider
private/
private/var/
private/var/run/
private/var/run/utmpx
private/var/run/._utmpx

sent 173 bytes  received 50 bytes  446.00 bytes/sec
total size is 3768  speedup is 16.90
Fnished.

Note that the copied files have the same meta information (e.g. permission, extended attributes, or etc.) as their original files.
```
Now it seems like it was found and collected, but it is not there in the output folder. If you try to select DMG output, then DMG creation fails, probably because the size is too small.

```
ykhatri@Balloon code % ls -alR 192-168-1-103_20210711_144142
total 16
drwxr-xr-x   4 root     staff  128 11 Jul 14:41 .
drwxr-xr-x  14 ykhatri  staff  448 11 Jul 14:41 ..
-rw-r--r--   1 root     staff  226 11 Jul 14:41 artifact_file_stat.csv
-rw-r--r--   1 root     staff  127 11 Jul 14:41 copy_artifact_files.log
ykhatri@Balloon code % 
```

**Comment by mnrkbys** [comment]
Actually, the debug option enables the dry-run option of the rsync command. Therefore, it is correct that files are not copied in debug mode.
However, this situation is very confusing, so I will add the dry-run option to macosac.

For DMG option, there is a bug that occurs when the total size of the files to be backed up is too small.
I will fix it to create a DMG file with a size of at least 1MB, formatted with JHFS+.

**Comment by mnrkbys** [comment]
I've fixed.
