### ISSUE TITLE
Chrome Extension not totally captured

### ISSUE THREAD

**Issue by 4NSIK1** [mnrkbys/macosac#9]
The path depth for Chrome Extensions is not deep enough to gather all files from Chrome Extensions. 
Currently it is 
file2_7 = /Users/*/Library/Application Support/Google/Chrome/*/Extensions/*/*/*

Recommended is another two levels deep
file2_9 = /Users/*/Library/Application Support/Google/Chrome/*/Extensions/*/*/*/*
file2_10 = /Users/*/Library/Application Support/Google/Chrome/*/Extensions/*/*/*/*/*

**Comment by mnrkbys** [comment]
Your examples seems broken.
Can you give specific examples of problems that occur?

**Comment by 4NSIK1** [comment]
Hi Minoru,
Sorry, Github markup changed the formatting.
When I did a capture with the 'Chrome' category, there were some folders in the Extensions directory that it did not collect using the current macosac.ini 
file2_7 = /Users/\*/Library/Application Support/Google/Chrome/\*/Extensions/\*/\*/\*
eg.
Extensions
-(extension name)
--(extension version)
---html
----(files in this folder were missed)
---css
----(files in this folder were missed)

My suggestion was to add two extra entries in the macosac.ini file for two deeper levels of folders/files
file2_9 = /Users/\*/Library/Application Support/Google/Chrome/\*/Extensions/\*/\*/\*/\*
file2_10 = /Users/\*/Library/Application Support/Google/Chrome/\*/Extensions/\*/\*/\*/\*/\*
This then collects files as shown below
Extensions
-(extension name)
--(extension version)
---html
----window.html
---css
----layout.css
 
Thanks for all your work on this capture script. It is really great.

**Comment by mnrkbys** [comment]
Sorry for the late response.
I have updated the code to collect files recursively.
